Create table Products (
    id serial Primary key,
    type, text,
    subtype text,
    image varchar(10000),
    image2 varchar(10000),
    description text,
    details text,
    name varchar(200),
    price decimal
)

create table users (
    id serial primary key,
    user_name varchar(180),
    email varchar(180),
    picture text,
    auth_id text
);

Create table Cart(
    id serial Primary key,
    product_id integer,
    user_id integer,
    image text,
    name text, 
    price integer

)


insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shoe', 'Golf', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw4e6efe76/FJ_50101_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw8862a721/FJ_50101_02.png?sw=650&sh=650&sm=fit', 'The definition of a classic golf shoe. Paying homage to the heritage and history of both FJ and the game of golf, these golf shoes deliver a perfect blend of performance and luxury on the course.', 'Calfskin Leather, Goodyear Welted Construction, Full Leather Linings + Outsole, Cork Underlay Cushioing, Exquisite Details + Finishes.', 'Shield Tip /White Scotch Grain', 750);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shoe', 'Golf', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwb1d3b44b/FJ_50102_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw41e018f6/FJ_50102_02.png?sw=650&sh=650&sm=fit', 'The definition of a classic golf shoe. Paying homage to the heritage and history of both FJ and the game of golf, these golf shoes deliver a perfect blend of performance and luxury on the course.', 'Calfskin Leather, Goodyear Welted Construction, Full Leather Linings + Outsole, Cork Underlay Cushioing, Exquisite Details + Finishes.', 'Shield Tip/White and black scotch grain', 750);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shoe', 'Golf', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwe7e3d1ac/FJ_50103_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw3baa5530/FJ_50103_02.png?sw=650&sh=650&sm=fit', 'The definition of a classic golf shoe. Paying homage to the heritage and history of both FJ and the game of golf, these golf shoes deliver a perfect blend of performance and luxury on the course.', 'Calfskin Leather, Goodyear Welted Construction, Full Leather Linings + Outsole, Cork Underlay Cushioing, Exquisite Details + Finishes.', 'Shield Tip /Black Scotch Grain', 750);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shoe', 'Golf', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw7e48e7c0/FJ_50036_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwa4a4abf9/FJ_50036_02.png?sw=650&sh=650&sm=fit', 'The definition of a classic golf shoe. Paying homage to the heritage and history of both FJ and the game of golf, these golf shoes deliver a perfect blend of performance and luxury on the course.', 'Calfskin Leather, Goodyear Welted Construction, Full Leather Linings + Outsole, Cork Underlay Cushioing, Exquisite Details + Finishes.', 'Plain Toe Saddle. White/WhiteCroc Print', 750);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shoe', 'Golf', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw6ef8e60e/FJ_50037_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw9fefee87/FJ_50037_02.png?sw=650&sh=650&sm=fit', 'The definition of a classic golf shoe. Paying homage to the heritage and history of both FJ and the game of golf, these golf shoes deliver a perfect blend of performance and luxury on the course.', 'Calfskin Leather, Goodyear Welted Construction, Full Leather Linings + Outsole, Cork Underlay Cushioing, Exquisite Details + Finishes.', 'Plain Toe Saddle White/ Black Croc print', 750);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shoe', 'Golf', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw153e5546/FJ_50041_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwa9cf6fed/FJ_50041_02.png?sw=650&sh=650&sm=fit', 'The definition of a classic golf shoe. Paying homage to the heritage and history of both FJ and the game of golf, these golf shoes deliver a perfect blend of performance and luxury on the course.', 'Calfskin Leather, Goodyear Welted Construction, Full Leather Linings + Outsole, Cork Underlay Cushioing, Exquisite Details + Finishes.', 'Plain Toe Saddle Brown/Chestnut Croc Print', 750);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shoe', 'Golf', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwd745a849/FJ_50034_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw47bc9a38/FJ_50034_02.png?sw=650&sh=650&sm=fit', 'The definition of a classic golf shoe. Paying homage to the heritage and history of both FJ and the game of golf, these golf shoes deliver a perfect blend of performance and luxury on the course.', 'Calfskin Leather, Goodyear Welted Construction, Full Leather Linings + Outsole, Cork Underlay Cushioing, Exquisite Details + Finishes.', 'Plain Toe Saddle White/ Chestnut Croc Print', 750);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shoe', 'Golf', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw05b342ef/FJ_50035_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwbba1d008/FJ_50035_02.png?sw=650&sh=650&sm=fit', 'The definition of a classic golf shoe. Paying homage to the heritage and history of both FJ and the game of golf, these golf shoes deliver a perfect blend of performance and luxury on the course.', 'Calfskin Leather, Goodyear Welted Construction, Full Leather Linings + Outsole, Cork Underlay Cushioing, Exquisite Details + Finishes.', 'Plain Toe saddle black/black croc paint', 750);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shoe', 'Golf', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw05b342ef/FJ_50035_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwbba1d008/FJ_50035_02.png?sw=650&sh=650&sm=fit', 'The definition of a classic golf shoe. Paying homage to the heritage and history of both FJ and the game of golf, these golf shoes deliver a perfect blend of performance and luxury on the course.', 'Calfskin Leather, Goodyear Welted Construction, Full Leather Linings + Outsole, Cork Underlay Cushioing, Exquisite Details + Finishes.', 'Plain Toe saddle black/black croc paint', 750);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shoe', 'Dress', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw76f94c3f/FJ_79601_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwb42ee904/FJ_79601_02.png?sw=650&sh=650&sm=fit', 'Class. Style. Craftsmanship. Add in the luxury of Italian calfskin leather uppers and you have a dress shoe fit for the most important occasion.', 'Calfskin Leather, Goodyear Welted Construction, Full Leather Linings + Outsole, Cork Underlay Cushioing, Exquisite Details + Finishes.', 'double Monk strap Cognac', 595);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shoe', 'Dress', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw76f94c3f/FJ_79601_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwb42ee904/FJ_79601_02.png?sw=650&sh=650&sm=fit', 'Class. Style. Craftsmanship. Add in the luxury of Italian calfskin leather uppers and you have a dress shoe fit for the most important occasion.', 'Calfskin Leather, Goodyear Welted Construction, Full Leather Linings + Outsole, Cork Underlay Cushioing, Exquisite Details + Finishes.', 'double Monk strap Navy', 595)
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shoe', 'Dress', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw42ba8be1/FJ_79701_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw18540a05/FJ_79701_02.png?sw=650&sh=650&sm=fit', 'Class. Style. Craftsmanship. Add in the luxury of Italian calfskin leather uppers and you have a dress shoe fit for the most important occasion.', 'Calfskin Leather, Goodyear Welted Construction, Full Leather Linings + Outsole, Cork Underlay Cushioing, Exquisite Details + Finishes.', 'Wink tip Blucher Walnut/cognac', 595);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shoe', 'Dress', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwbab16fe4/FJ_79700_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw56d7d7b7/FJ_79700_02.png?sw=650&sh=650&sm=fit', 'Class. Style. Craftsmanship. Add in the luxury of Italian calfskin leather uppers and you have a dress shoe fit for the most important occasion.', 'Calfskin Leather, Goodyear Welted Construction, Full Leather Linings + Outsole, Cork Underlay Cushioing, Exquisite Details + Finishes.', 'Wing Tip Blucher cognac', 595);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shoe', 'Dress', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwfd1a5fb0/FJ_79702_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwecd95d7f/FJ_79702_02.png?sw=650&sh=650&sm=fit', 'Class. Style. Craftsmanship. Add in the luxury of Italian calfskin leather uppers and you have a dress shoe fit for the most important occasion.', 'Calfskin Leather, Goodyear Welted Construction, Full Leather Linings + Outsole, Cork Underlay Cushioing, Exquisite Details + Finishes.', 'Wing tip Blucher black', 595);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shoe', 'Dress', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw6cfea4e4/FJ_79500_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwf306485a/FJ_79500_02.png?sw=650&sh=650&sm=fit', 'Class. Style. Craftsmanship. Add in the luxury of Italian calfskin leather uppers and you have a dress shoe fit for the most important occasion.', 'Calfskin Leather, Goodyear Welted Construction, Full Leather Linings + Outsole, Cork Underlay Cushioing, Exquisite Details + Finishes.', 'Straight Tip Dress Walnut', 595);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shoe', 'Dress', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwa617b83e/FJ_79501_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwb92ad268/FJ_79501_02.png?sw=650&sh=650&sm=fit', 'Class. Style. Craftsmanship. Add in the luxury of Italian calfskin leather uppers and you have a dress shoe fit for the most important occasion.', 'Calfskin Leather, Goodyear Welted Construction, Full Leather Linings + Outsole, Cork Underlay Cushioing, Exquisite Details + Finishes.', 'Straight Tip Dress Black', 595);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shoe', 'Casual', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw37481f08/FJ_79400_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwd9dd269e/FJ_79400_02.png?sw=650&sh=650&sm=fit', 'The finest materials, a designer''s flair and the stamp of the #1 shoe in golf, makes for a fun and versatile off-course option.', 'Full Grain Suede Leather, Silowelt Construction, Full Leather Linings, Cork Underlay Cushioning, Exquisite Details + Finishes', 'Wing tip suede', 475);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shoe', 'Casual', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw74759675/FJ_79402_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwf5de3c7a/FJ_79402_02.png?sw=650&sh=650&sm=fit', 'The finest materials, a designer''s flair and the stamp of the #1 shoe in golf, makes for a fun and versatile off-course option.', 'Full Grain Suede Leather, Silowelt Construction, Full Leather Linings, Cork Underlay Cushioning, Exquisite Details + Finishes', 'Wing Tip Suede blue suede', 475);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shoe', 'Casual', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dweb5abb52/FJ_79401_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw032e01de/FJ_79401_02.png?sw=650&sh=650&sm=fit', 'The finest materials, a designer''s flair and the stamp of the #1 shoe in golf, makes for a fun and versatile off-course option.', 'Full Grain Suede Leather, Silowelt Construction, Full Leather Linings, Cork Underlay Cushioning, Exquisite Details + Finishes', 'Wing Tip Suede red suede', 475);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'Golf Shirt', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwb439a9ba/FJ_25639_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw48872281/FJ_25639_02.png?sw=650&sh=650&sm=fit', 'Mercerized cotton and spandex are blended into a premium lisle knit shirt. Refined details and clean construction make this piece a modern classic.', 'Self Fabric Collar, Smooth Placket, Genuine Shell Buttons, Side Vents on Hem, Imported 88% cotton, 12% spandex', 'Stretch Lisle Smooth Placket shirt Blue Ink', 125);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'Golf Shirt', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw02250475/FJ_25637_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw1637e568/FJ_25637_02.png?sw=650&sh=650&sm=fit', 'Our luxurious solid shirt is knit in a soft, yet substantial blend of supima cotton and spandex. Refined details and clean construction make this piece a modern classic that out-performs your expectations.', 'Self Fabric Collar, Genuine Shell Buttons, Patch Pocket, Side Vents on Hem, imported, 80% Supima Cotton, 20% Spandex', 'Supima Cotton Knit Shirt with Pocket Navy', 125);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'Golf Shirt', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw43d69ef2/FJ_25641_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw4a502367/FJ_25641_02.png?sw=650&sh=650&sm=fit', 'Our stretch pique knit shirt is sporty, yet elegant. Note the set-on placket and self-fabric collar with our signature 1857 neck trim. Details make all the difference.', 'Self Fabric Collar, Genuine Shell Buttons, Patch Pocket, Side Vents on Hem, imported, 94% cotton, 6% Spandex', 'Stretch Pique Shirt with Set on Placket Heather Grey', 125);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'Golf Shirt', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwa2b2e149/FJ_25648_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwfe799604/FJ_25648_02.png?sw=650&sh=650&sm=fit', 'Tiny pin dots are knit into our mercerized cotton shirt. So tasteful, you can dress it up and appear quite elegant. But don''t forget, the shirt looks great paired with the sportier pieces of your wardrobe.', 'Self Fabric Collar, Smooth Placket, Genuine Shell Buttons, Side Vents on Hem, Imported, 95% Mercerized Cotton, 5% Spandex', 'Pin dot Jacquard Shirt', 135);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'Golf Shirt', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwd0d59362/FJ_25645_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwda193826/FJ_25645_02.png?sw=650&sh=650&sm=fit', 'Your favorite shirt is elevated with subtle details: genuine shell buttons, set-on placket and our 1857 stripe neck trim. The luxurious cotton knit fabric will perform and always feel great.', 'Self Fabric Collar, Set-On Placket, Genuine Shell Buttons, Side Vents on Hem, Imported, 80% Mercerized Cotton, 20% Spandex', 'Lisle Mini Feeder Stripe Shirt', 135);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'Golf Shirt', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwe00e0dc5/FJ_25650_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw0c3bdb7e/FJ_25650_02.png?sw=650&sh=650&sm=fit', 'A good looking stripe shirt is a mainstay of your wardrobe. The premium mercerized lisle knit with added spandex makes this one special. You''ll find numerous ways to wear this shirt and look great.', 'Self Fabric Collar, Top Stitched Placket, Genuine Shell Buttons, Side Vents on Hem, Imported, 95% Mercerized Cotton, 5% Spandex', 'Stretch Lisle Multi Stripe Shirt', 135);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'Golf Shirt', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw1738bde5/FJ_25649_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw76bba004/FJ_25649_02.png?sw=650&sh=650&sm=fit', 'Alternating single stitches of color create our subtle birds eye jacquard pattern. The sheen and softness of the mercerized knit are incredibly appealing. Spread collar styling with 1857 stripe trim sets this one apart.', 'Self Fabric Collar, Top Stitched Placket, Genuine Shell Buttons, Side Vents on Hem, Imported, 95% Mercerized Cotton, 5% Spandex', 'Birdseye Jacquard Knit Shirt', 135);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'Golf Shirt', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw562f8e87/FJ_25643_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw11041daf/FJ_25643_02.png?sw=650&sh=650&sm=fit', 'A classic pencil stripe is yarn dyed into our premium 1857 lisle knit. This shirt is a wardrobe staple that never goes out of style. Clean, modern design and stretch fabric update the traditional.', 'Self Fabric Collar, Top Stitched Placket, Genuine Shell Buttons, Side Vents on Hem, Imported, 95% Mercerized Cotton, 5% Spandex', 'Stretch Lisle Mini Pencil Stripe Shirt', 135);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'Golf Shirt', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw3490ab4d/FJ_27837_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw05ce5261/FJ_27837_02.png?sw=650&sh=650&sm=fit', 'Layered or worn on its own, this long sleeve knit will feel incredible. The fine gauge blend of luxury fibers is second to none. Understated styling allows the fabric to be the star.', 'Self Fabric Collar, set-on Placket, genuine shell buttons, open hem, imported, 80%cotton, 10% Silk, 10% cashmere', 'Cashmere Blend Knit Shirt Blue Ink', 135);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'Dress Shirt', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw8798cbc6/FJ_27845_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw27d03c1b/FJ_27845_02.png?sw=650&sh=650&sm=fit', 'A classic button down shirt elevated by premium fabric and understated details. Yarn-dyed gingham check in multiple colors.', 'Button-Down Collar, Adjustable Button Cuffs, Genuine Shell Buttons, Imported, 90% cotton, 10% spandex', 'Stretch Cotton Gingham Woven Shirt', 165);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'Dress Shirt', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw889d4d42/FJ_27844_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw1f65de8c/FJ_27844_02.png?sw=650&sh=650&sm=fit', 'A classic button down shirt elevated by premium fabric and understated details. Yarn-dyed plaid with multiple colors.', 'Button-Down Collar, Adjustable Button Cuffs, Genuine Shell Buttons, Imported, 90% cotton, 10% spandex', 'Stretch Cotton Plaid Woven Navy Base Plaid', 165);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'Dress Shirt', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw3d274cb0/FJ_27843_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw97d24061/FJ_27843_02.png?sw=650&sh=650&sm=fit', 'A classic button down shirt elevated by premium fabric and understated details. Yarn-dyed multi check in multiple colors.', 'Button-Down Collar, Adjustable Button Cuffs, Genuine Shell Buttons, Imported, 90% cotton, 10% spandex', 'Stretch Cotton Woven Shirt WHITE / BLUE INK / NAVY / RED', 165);



insert into Products (type, subtype, image, image2, description, details, name, price) values ('', '', '', '', '', '', '', 750);




insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'Dress Shirt', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw504405ff/FJ_27847_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw560bf5c3/FJ_27847_02.png?sw=650&sh=650&sm=fit', 'A classic button down shirt elevated by premium fabric and understated details. Yarn-dyed micro check in multiple colors.', 'Button-Down Collar, Adjustable Button Cuffs, Genuine Shell Buttons, Imported, 90% cotton, 10% spandex', 'Stretch Cotton Micro-check Shirt BLUE INK / WHITE', 165);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'Dress Shirt', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwb4a71a8d/FJ_27848_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw41559efe/FJ_27848_02.png?sw=650&sh=650&sm=fit', 'A classic button down shirt elevated by premium fabric and understated details. Yarn-dyed micro stripe with a chambray finish.', 'Button-Down Collar, Adjustable Button Cuffs, Genuine Shell Buttons, Imported, 97% cotton, 3% spandex', 'Stretch Cotton Micro-Stripe Shirt', 165);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'Mid Layer', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwa4f3b80d/FJ_27842_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwbca9cdc8/FJ_27842_02.png?sw=650&sh=650&sm=fit', 'The clever use of each fabric side helped to create this full-zip double layer vest with contrast binding trim. A pop of color was added to the zipper placket. Layer the vest over a woven plaid shirt with the sleeves rolled up.', 'Stand Up Collar, Open Front Pockets, Full-Zip, Imported, 77% Cotton, 15% wool, 8% Micro Poly', 'Double Layer Full-Zip Vest Navy /Heather Grey', 175);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'Mid Layer', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw292cb84e/FJ_27839_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw44725741/FJ_27839_02.png?sw=650&sh=650&sm=fit', 'The clever use of each fabric side creates contrast and a binding trim on this mid layer. A zipper placket and chest pocket add a pop of color which allows for layering over your favorite shirt.', 'Quarter-zip stand up collar, Zipper Chest Pocket, Imported 77% Cotton, 15% Wool, 8% Micro Poly', 'Double layer half zip mid layer Navy', 225);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'Mid Layer', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwe350b213/FJ_27838_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw92c28e44/FJ_27838_02.png?sw=650&sh=650&sm=fit', 'The quarter zip mid layer is made from a double layer knit. The fabric is 2-sided: solid in color reversing to a subtle pattern in the sleeves. The pattern for the body compliments the solid sleeves and collar.', 'Rib Knit Collar, 2-color Zipper, Open Hem Bottom, Imported, 87% Cotton, 7% nylon, 6% Spandex', 'Cotton blend Quarter Zip Midlayer Blue Ink / Navy', 225);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'Sweater', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw78ec6456/FJ_24757_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwa74c534d/FJ_24757_02.png?sw=650&sh=650&sm=fit', 'Using fresh colors and a luxuriously fine gauge, helps elevate this classic crewneck sweater. Wear this piece over your woven button down shirt, then slip it under a blazer.', 'Fine Gauge Knit, Rib Neckline+Cuffs and Waistband, 1857 Stripe Trim Inside Neck, Imported, 70% Cashmere, 30% Nylon', 'cashmere Crewneck Sweater Red', 425);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'Sweater', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw15288879/FJ_24761_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw113e700c/FJ_24761_02.png?sw=650&sh=650&sm=fit', 'The style of a vintage sweatshirt is reworked into a soft cashmere blend sweater. Dress it up or casually pair with jeans. This may become your favorite sweater.', 'Mid weight Cashmere Rib Waistband+Cuffs and crewneck, Rib stitch side panels, 1857 stripe Trim inside neck, Raised Raglan Shoulder Seams, imported, 75% Cashmere, 19% Nylon, 6% spandex', 'Cashmere raglan Crewneck Sweater Heather grey', 350);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'Sweater', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw35b85216/FJ_24764_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw5c5baeec/FJ_24764_02.png?sw=650&sh=650&sm=fit', 'Experience ultimate luxury; the heavy weight cashmere achieves soft comfort with this knit hoodie. Wear this under a vest, but you''ll also think it''s excellent on its own.', 'Heavy Knit Cashmere, Double Layer Hood, Pass-Through Front Pockets, Rib Waistband+cuffs, 1857 Trim inside neck, imported, 92% Cashmere, 6% nylon 2% spandex.', 'Cashmere Hoodie Sweater Heather Grey', 395);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'Sweater', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw01c84381/FJ_24760_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw6b27d2a7/FJ_24760_02.png?sw=650&sh=650&sm=fit', 'Details along the V-neck helps make this classic sweater special. Wear this fine gauge piece over a favorite shirt, then slip on your blazer.', 'Fine Gauge Knit, Rib Neckline+Cuffs and waistband, 1857 Stripe Trim inside neck, Color Accent on V-neck, Imported, 70% Cashmere, 30% Nylon;', 'Cashmere Trimmed V-Neck Sweater Navy', 325);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'Sweater', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwdd03a0ba/FJ_24763_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw52ffc560/FJ_24763_02.png?sw=650&sh=650&sm=fit', 'We''ve crafted the old school 5-button cardigan sweater vest for a perfect fit using a soft cashmere blend and knit the back in a subtle rib texture. This is not your high school English teacher''s sweater vest.', 'Medium Wight Knit, Front Pockets, Genuine Shell Buttons, Imported, 75% Cashmere, 19% Nylon, 6% Spandex', 'Cashmere Cardigan Vest heather grey', 335);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'Sweater', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwa40893d1/FJ_24762_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw57ba99de/FJ_24762_02.png?sw=650&sh=650&sm=fit', 'We''ve crafted the old school 5-button cardigan sweater for a perfect fit. Perfectly crafted in a soft cashmere blend with a rib texture back panel. Pair it with a button down and dress pants or a T-shirt with jeans.', 'Medium Weight Knit, Front Pockets, Genuine Shell Buttons, Imported, 75% Cashmere, 19% Nylon, 6% Spandex', 'Cashmere Cardigan Sweater Navy', 385);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'Bottom', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw2dd5ae69/FJ_24474_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw9a2aad7a/FJ_24474_02.png?sw=650&sh=650&sm=fit', 'These luxury trousers are tailored from a fine wool woven with a bit of stretch. Less topstitching achieves a clean and modern look. Pair these trousers with a cashmere sweater and you''ll be favorably impressed.', 'Super 80’s Wool, Straight Leg+ flat front fit, angled front pockets, besom Back pockets+Button Closure, Unfinished Hem, Imported, 97% Wool, 3% Lycra', 'Stretch Wool Trousers Charcoal', 185);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'Bottom', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwea98df3c/FJ_24475_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw3cc7e234/FJ_24475_02.png?sw=650&sh=650&sm=fit', 'These luxury trousers are tailored from a fine wool woven with a bit of stretch. Less topstitching achieves a clean and modern look. Pair these trousers with a cashmere sweater and you''ll be favorably impressed.', 'Super 80’s Wool, Straight Leg+ flat front fit, angled front pockets, besom Back pockets+Button Closure, Unfinished Hem, Imported, 97% Wool, 3% Lycra', 'Stretch Wool Trousers Navy subtle check', 185);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'Outerwear', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwf7a314d8/FJ_27849_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw46755238/FJ_27849_02.png?sw=650&sh=650&sm=fit', 'This multi-tasking vest is lined with soft knit fabric, trimmed with stretch rib and knit side panels for extra mobility. By utilizing mid-weight insulation, you can easily layer the vest under a jacket or over a hoodie.', 'Woven Stretch Shell, Cotton Blend Lining, Two-Way Full Zip Placket, Zipper front pockets, Rib Knit Trim+Side Panels, Imported, 84% Nylon, 16% PU', 'Full-zip Quilted Vest Navy', 325);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'Outerwear', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwcb4b6a48/FJ_25015_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dwc86e7380/FJ_25015_02.png?sw=650&sh=650&sm=fit', 'We''ve taken the softest fleece knit mid layer and quilted the front with a stretch woven fabric. A nice mix of textures helps reduce weight and bulk. Wear this piece for added warmth when layering.', 'self Fabric Collar+Cuffs and Waistband, Woven Front Panel, Full=Zip Opening, Front Pockets, Imported, 67% Modal, 28% Cotton, 5% Spandex.', 'Full-Zip Hybrid Jacket Navy', 325);
insert into Products (type, subtype, image, image2, description, details, name, price) values ('Shirt', 'OuterWear', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw975489f0/FJ_25016_01.png?sw=650&sh=650&sm=fit', 'https://sits-pod38.demandware.net/dw/image/v2/AAZW_PRD/on/demandware.static/-/Sites-footjoy-master/default/dw044b2b21/FJ_25016_02.png?sw=650&sh=650&sm=fit', 'description: Fully loaded but still tasteful, you’ll enjoy the many details this jacket has to offer. Numerous pockets, 1857 snap closures, a two-way zipper placket and a storm flap just to name a few. Also the inside seams are bound with colorful thread.', 'details: Stand Up Collar, Woven Nylon Shell, Midweigth Insulation, Flap Hand Pockets+Side Entry, Snap Placket+Storm Flap, Imported, 84% nylon, 16% PU;', 'Quilted Stretch Woven Jacket navy', 395);

insert into Products (type, subtype, image, image2, description, details, name, price) values (49, '', '', '', '', '', '', '', 750);